/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'status' : string,
  'studentId' : string,
  'studentName' : string,
  'date' : string,
  'time' : string,
  'timestamp' : bigint,
  'course' : string,
}
export interface FaceData {
  'studentId' : string,
  'faceImage' : string,
  'enrolledAt' : bigint,
}
export interface Student {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'phone' : string,
  'course' : string,
}
export interface UserProfile { 'username' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addStudent' : ActorMethod<[Student], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteStudent' : ActorMethod<[string], undefined>,
  'enrollFace' : ActorMethod<[FaceData], undefined>,
  'getAllAttendanceRecords' : ActorMethod<[], Array<AttendanceRecord>>,
  'getAllFaces' : ActorMethod<[], Array<FaceData>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAttendanceRecord' : ActorMethod<[string], AttendanceRecord>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFace' : ActorMethod<[string], FaceData>,
  'getStudent' : ActorMethod<[string], Student>,
  'getTodaysStats' : ActorMethod<
    [string],
    {
      'totalStudents' : bigint,
      'presentCount' : bigint,
      'absentCount' : bigint,
    }
  >,
  'getUnmarkedStudents' : ActorMethod<[string], Array<Student>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAttendance' : ActorMethod<[AttendanceRecord], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateStudent' : ActorMethod<[string, Student], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];