/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Student = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'phone' : IDL.Text,
  'course' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FaceData = IDL.Record({
  'studentId' : IDL.Text,
  'faceImage' : IDL.Text,
  'enrolledAt' : IDL.Int,
});
export const AttendanceRecord = IDL.Record({
  'status' : IDL.Text,
  'studentId' : IDL.Text,
  'studentName' : IDL.Text,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'timestamp' : IDL.Int,
  'course' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'username' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStudent' : IDL.Func([Student], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteStudent' : IDL.Func([IDL.Text], [], []),
  'enrollFace' : IDL.Func([FaceData], [], []),
  'getAllAttendanceRecords' : IDL.Func(
      [],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAllFaces' : IDL.Func([], [IDL.Vec(FaceData)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAttendanceRecord' : IDL.Func([IDL.Text], [AttendanceRecord], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFace' : IDL.Func([IDL.Text], [FaceData], ['query']),
  'getStudent' : IDL.Func([IDL.Text], [Student], ['query']),
  'getTodaysStats' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'totalStudents' : IDL.Nat,
          'presentCount' : IDL.Nat,
          'absentCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUnmarkedStudents' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func([AttendanceRecord], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateStudent' : IDL.Func([IDL.Text, Student], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Student = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'phone' : IDL.Text,
    'course' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FaceData = IDL.Record({
    'studentId' : IDL.Text,
    'faceImage' : IDL.Text,
    'enrolledAt' : IDL.Int,
  });
  const AttendanceRecord = IDL.Record({
    'status' : IDL.Text,
    'studentId' : IDL.Text,
    'studentName' : IDL.Text,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'timestamp' : IDL.Int,
    'course' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'username' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStudent' : IDL.Func([Student], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteStudent' : IDL.Func([IDL.Text], [], []),
    'enrollFace' : IDL.Func([FaceData], [], []),
    'getAllAttendanceRecords' : IDL.Func(
        [],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAllFaces' : IDL.Func([], [IDL.Vec(FaceData)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAttendanceRecord' : IDL.Func([IDL.Text], [AttendanceRecord], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFace' : IDL.Func([IDL.Text], [FaceData], ['query']),
    'getStudent' : IDL.Func([IDL.Text], [Student], ['query']),
    'getTodaysStats' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'totalStudents' : IDL.Nat,
            'presentCount' : IDL.Nat,
            'absentCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUnmarkedStudents' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func([AttendanceRecord], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateStudent' : IDL.Func([IDL.Text, Student], [], []),
  });
};

export const init = ({ IDL }) => { return []; };